import Url from "../../support/PageObjects/url"
import Body from "../../support/PageObjects/body"
describe('Body', () => {
  let url = new Url()
  let body = new Body()
    beforeEach(() => {
      url.homePage()
      cy.title().should('eq', 'Aspiritech – Build it. Break it. Our team tests it. Software QA & Data Services')
      cy.get('h3')
      .contains('Support Our Neurodiverse Team').should('be.visible')
    })
    it('should click through each link in the body', () => {
        cy.section('Universal Search Bar')
        body.searchBose()
        cy.get('h1').contains('Search Results for: Bose')
        cy.get('div').contains('Recent Posts').should('be.visible')
        cy.title().should('eq', 'Search Results for “Bose” – Aspiritech')
        cy.url().should('include', 'Bose')
        body.searchContact()
        cy.get('h1').contains('Search Results for: Contact')
        cy.get('div').contains('Recent Posts').should('be.visible')
        cy.title().should('eq', 'Search Results for “Contact” – Aspiritech')
        cy.url().should('include', 'Contact')
        body.searchDonation()
        cy.get('h1').contains('Search Results for: Donation')
        cy.get('div').contains('Recent Posts').should('be.visible')
        cy.title().should('eq', 'Search Results for “Donation” – Aspiritech')
        cy.url().should('include', 'Donation')

        cy.section('Our Clients')
        cy.get('h2').contains('Our Clients').should('be.visible')
        cy.get('.elementor-heading-title > a').contains('View case studies').click()
        cy.get('h1').contains('Case Studies').should('be.visible')
        cy.title().should('eq', 'Case Studies – Aspiritech')
        cy.url().should('include', 'case-studies')
        cy.go('back')
        cy.get('div.elementor-widget-wrap').contains('Bose').click()
        cy.title().should('eq', 'Bose Case Study – Aspiritech')
        cy.url().should('include', 'bose-case-study')
        cy.get('div.elementor-widget-wrap').contains('Otus').click()
        cy.title().should('eq', 'Otus Case Study – Aspiritech')
        cy.url().should('include', 'otus-case-study')
        cy.get('div.elementor-widget-wrap').contains('JP Morgan Chase').click()
        cy.title().should('eq', 'JP Morgan Chase Case Study – Aspiritech')
        cy.url().should('include', 'jpmc-case-study')
        cy.get('div.elementor-widget-wrap').contains('Basecamp').click()
        cy.title().should('eq', 'Basecamp Case Study – Aspiritech')
        cy.url().should('include', 'basecamp-case-study')
        cy.get('div.elementor-widget-wrap').contains('AbbVie').click()
        cy.title().should('eq', 'AbbVie Case Study – Aspiritech')
        cy.url().should('include', 'abbvie-case-study')
        cy.get('div.elementor-widget-wrap').contains('Goldman Sachs').click()
        cy.title().should('eq', 'Goldman Sachs Case Study – Aspiritech')
        cy.url().should('include', 'goldman-sachs-case-study')
        cy.get('div.elementor-widget-wrap').contains('Source America').click()
        cy.title().should('eq', 'Page not found – Aspiritech')
        cy.url().should('include', 'source-america-case-study-2')
        cy.get('div.elementor-widget-wrap').contains('hsri').click()
        cy.title().should('eq', 'HSRI Case Study – Aspiritech')
        cy.url().should('include', 'hsri-case-study')
        
        cy.section('Our Extertise')
        cy.get('h2').contains('Our Expertise').should('be.visible')
        cy.get('a.elementor-button').contains('Accessibility').click()
        cy.get('h1').contains('Accessibility Testing: Design, UX, Usability, & WCAG Conformance').should('be.visible')
        cy.title().should('eq', 'Accessibility Testing: Design, UX, Usability, & WCAG Conformance – Aspiritech')
        cy.url().should('include', 'accessibility')
        cy.get('a.elementor-button').contains('Audio Testing').click()
        cy.get('h1').contains('Audio & Hardware Testing: Speakers, Headphones, & Connectivity').should('be.visible')
        cy.title('eq', 'Audio & Hardware Testing: Speakers, Headphones, & Connectivity – Aspiritech')
        cy.url().should('include', 'audio-testing')
        cy.get('a.elementor-button').contains('Quality Assurance').click()
        cy.get('h1').contains('Software Quality Assurance').should('be.visible')
        cy.title().should('eq', 'Software Quality Assurance – Aspiritech')
        cy.url().should('include', 'quality-assurance')
        cy.get('a.elementor-button').contains('Data Services').click()
        cy.get('h1').contains('Data Services: Data Annotation, Data Labeling, and Data Validation.').should('be.visible')
        cy.title().should('eq', 'Data Services: Data Annotation, Data Labeling, and Data Validation. – Aspiritech')
        cy.url().should('include', 'data-services')
        
        cy.section('Clients')
        cy.step('Click all links for Clients')
        cy.get('h2').contains('Clients').should('be.visible')
        body.clientsToggle()
        cy.get('a.elementor-item').contains('About').click({force: true})
        cy.title().should('eq', 'About Us – Aspiritech')
        cy.url().should('include', 'about-us')
        cy.get('a.elementor-item').contains('Aspiritech Press').click({force: true})
        cy.title().should('eq', 'Aspiritech Press – Aspiritech')
        cy.url().should('include', 'aspiritech-press')
        cy.get('a.elementor-item').contains('Get In Touch').click({force: true})
        cy.title().should('eq', 'Contact Us – Aspiritech')
        cy.url().should('include', 'contact-us')
        cy.get('a.elementor-item').contains('FAQs').click({force: true})
        cy.title().should('eq', 'Frequently Asked Questions (FAQs) – Aspiritech')
        cy.url().should('include', 'faqs')
        
        cy.section('Why Aspiritech?')
        cy.step('Click all links for Why Aspiritech?')
        cy.get('h2').contains('Why Aspiritech?').should('be.visible')
        body.whyaspiritechToggle()
        cy.get('a.elementor-item').contains('Our Story').click({force: true})
        cy.title().should('eq', 'Our Story – Aspiritech')
        cy.url().should('include', 'our-story')
        cy.get('a.elementor-item').contains('Leadership').click({force: true})
        cy.title().should('eq', 'Leadership – Aspiritech')
        cy.url().should('include', 'leadership')
        cy.get('a.elementor-item').contains('Team Members').click({force: true})
        cy.title().should('eq', 'Team Members – Aspiritech')
        cy.url().should('include', 'team-members')
        cy.get('a.elementor-item').contains('Support Our Mission').click({force: true})
        cy.title().should('eq', 'Support Our Mission – Aspiritech')
        cy.url().should('include', 'support-our-mission')
        
        cy.section('Resources')
        cy.step('Click all links for Resources')
        cy.get('h2').contains('Resources').should('be.visible')
        body.resourcesToggle()
        cy.get('a.elementor-item').contains('Neurodiversity Library').click({force: true})
        cy.title().should('eq', 'Neurodiversity Resource Library – Aspiritech')
        cy.url().should('include', 'neurodiversity-resource-library')
        cy.get('a.elementor-item').contains('Upcoming Events').click({force: true})
        cy.title().should('eq', 'Events – Aspiritech')
        cy.url().should('include', 'events')
        cy.get('a.elementor-item').contains('News').click({force: true})
        cy.title().should('eq', 'News & Resources – Aspiritech')
        cy.url().should('include', 'news')
        cy.get('a.elementor-item').contains('Stepping Up & Out').click({force: true})
        cy.title().should('eq', 'About the Stepping Up & Out (SUO) Program – Aspiritech')
        cy.url().should('include', 'about-the-stepping-up-out-suo-program')
        
        cy.section('Buttons')
        cy.step('Click Buttons')
        cy.get('#work-with-us').contains('Hire Aspiritech').click()
        cy.title().should('eq', 'Contact Us – Aspiritech')
        cy.url().should('include', 'contact-us')
        cy.get('a.elementor-button').contains('Donate Now').click()
        cy.title().should('eq', 'Support Our Mission – Aspiritech')
        cy.url().should('include', '#donate-now')
    })
})