describe('Body', () => {
    beforeEach(() => {
      cy.visit('https://aspiritech.org')
      cy.title().should('eq', 'Aspiritech – Build it. Break it. Our team tests it. Software QA & Data Services')
      cy.get('.elementor-element-a0fbbb9 > .elementor-widget-container > .elementor-heading-title')
      .contains('Support Our Neurodiverse Team').should('be.visible')
    })
    it('should click through each link in the body', () => {
        cy.section('Our Clients')
        cy.get('.elementor-element-56ca18f4 > .elementor-widget-container > .elementor-heading-title > a').click()
        cy.get('.elementor-element-04c4dba > .elementor-widget-container > .elementor-heading-title').contains('Case Studies').should('be.visible')
        cy.title().should('eq', 'Case Studies – Aspiritech')
        cy.url().should('include', 'case-studies')
        cy.section('Our Extertise')
        cy.get('.elementor-element-68b6f824 > .elementor-widget-wrap').contains('Accessibility').click()
        cy.get('.elementor-element-4fb348f1 > .elementor-widget-container > .elementor-heading-title').contains('Accessibility Testing: Design, UX, Usability, & WCAG Conformance').should('be.visible')
        cy.title().should('eq', 'Accessibility Testing: Design, UX, Usability, & WCAG Conformance – Aspiritech')
        cy.url().should('include', 'accessibility')
        cy.get('.elementor-element-b35a64b > .elementor-widget-wrap').contains('Audio Testing').click()
        cy.get('.elementor-element-68c0fc70 > .elementor-widget-container > .elementor-heading-title').contains('Audio & Hardware Testing: Speakers, Headphones, & Connectivity').should('be.visible')
        cy.title('eq', 'Audio & Hardware Testing: Speakers, Headphones, & Connectivity – Aspiritech')
        cy.url().should('include', 'audio-testing')
        cy.get('.elementor-element-73131894 > .elementor-widget-wrap').contains('Quality Assurance').click()
        cy.get('.elementor-element-3f7eeaa > .elementor-widget-container > .elementor-heading-title').contains('Software Quality Assurance').should('be.visible')
        cy.title().should('eq', 'Software Quality Assurance – Aspiritech')
        cy.url().should('include', 'quality-assurance')
        cy.get('.elementor-element-3cd87e61 > .elementor-widget-wrap').contains('Data Services').click()
        cy.get('.elementor-element-63b8939c > .elementor-widget-container > .elementor-heading-title').contains('Data Services: Data Annotation, Data Labeling, and Data Validation.').should('be.visible')
        cy.title().should('eq', 'Data Services: Data Annotation, Data Labeling, and Data Validation. – Aspiritech')
        cy.url().should('include', 'data-services')
        cy.section('Clients')
        cy.step('Click all links for Clients')
        cy.get('.elementor-element-5f13155 > .elementor-widget-container').should('be.visible')
        cy.get('.elementor-element-5f13155 > .elementor-widget-container > .elementor-menu-toggle').click()
        cy.get('#menu-2-5f13155 > .menu-item-5118 > .elementor-item').contains('About').click()
        cy.get('#menu-2-5f13155 > .menu-item-5117 > .elementor-item').contains('Aspiritech Press').click({force: true})
        cy.get('#menu-2-5f13155 > .menu-item-5119 > .elementor-item').contains('Get In Touch').click({force: true})
        cy.get('#menu-2-5f13155 > .menu-item-64 > .elementor-item').contains('FAQs').click({force: true})
        cy.section('Why Aspiritech?')
        cy.step('Click all links for Why Aspiritech?')
        cy.get('.elementor-element-7d64b0b > .elementor-widget-container').should('be.visible')
        cy.get('.elementor-element-7d64b0b > .elementor-widget-container > .elementor-menu-toggle').click()
        cy.get('#menu-2-7d64b0b > .menu-item-99 > .elementor-item').contains('Our Story').click()
        cy.get('#menu-2-7d64b0b > .menu-item-5123 > .elementor-item').contains('Leadership').click({force: true})
        cy.get('#menu-2-7d64b0b > .menu-item-5125 > .elementor-item').contains('Team Members').click({force: true})
        cy.get('#menu-2-7d64b0b > .menu-item-5124 > .elementor-item').contains('Support Our Mission').click({force: true})
        cy.section('Resources')
        cy.step('Click all links for Resources')
        cy.get('.elementor-element-542c894 > .elementor-widget-container').should('be.visible')
        cy.get('.elementor-element-542c894 > .elementor-widget-container > .elementor-menu-toggle').click()
        cy.get('#menu-2-542c894 > .menu-item-5129 > .elementor-item').contains('Neurodiversity Library').click()
        cy.get('#menu-2-542c894 > .menu-item-type-post_type > .elementor-item').contains('Upcoming Events').click({force: true})
        cy.get('#menu-2-542c894 > .menu-item-6404 > .elementor-item').contains('News').click({force: true})
        cy.get('#menu-2-542c894 > .menu-item-6405 > .elementor-item').contains('Stepping Up & Out').click({force: true})
        cy.section('Buttons')
        cy.step('Click Buttons')
        cy.get('#work-with-us').contains('Hire Aspiritech').click()
        cy.get('.elementor-element-fb921b0 > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Donate Now').click()
    })
})