describe('Footer Menu Test', () => {
    beforeEach(() => {
      cy.visit('https://aspiritech.org')
      cy.title().should('eq', 'Aspiritech – Build it. Break it. Our team tests it. Software QA & Data Services')
      cy.get('.elementor-element-a0fbbb9 > .elementor-widget-container > .elementor-heading-title')
      .contains('Support Our Neurodiverse Team').should('be.visible')
    })
    it('should click through the annual reports by year', () => {
        cy.get('.elementor-element-0fb3afa > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > p').contains('Aspiritech, NFP').should('be.visible')
        cy.contains('a', '2015').click()
        cy.go('back')
        cy.contains('a', '2016').click()
        cy.go('back')
        cy.contains('a', '2017').click()
        cy.go('back')
        cy.contains('a', '2018').click()
        cy.go('back')
        cy.contains('a', '2019').click()
        cy.go('back')
        cy.contains('a', '2020').click()
        cy.go('back')
        cy.contains('a', '2021').click()
        cy.go('back')
        cy.contains('a', '2022').click()
        cy.go('back')
    })
    it('should click through the rest of the footer links', () => {
        cy.get('.elementor-element-f5e176b > .elementor-widget-container > :nth-child(1) > a').click()
        cy.get('.elementor-4274 > .elementor-section > .elementor-container > .elementor-column > .elementor-widget-wrap').contains('404').should('be.visible')
        cy.title().should('eq', 'Page not found – Aspiritech')
        cy.url().should('include', 'sitemap_index.xml')
        cy.go('back')
        cy.get('.elementor-widget-container > :nth-child(2) > a').contains('Privacy').click()
        cy.get('h1').contains('Privacy Policy').should('be.visible')
        cy.title().should('eq', 'Privacy Policy – Aspiritech')
        cy.url().should('include', 'privacy-policy')
        cy.go('back')
        cy.get('.elementor-widget-container > :nth-child(3) > a').contains('Back to top').click()
    })
})