describe('Footer Menu Test', () => {
    beforeEach(() => {
      cy.visit('https://aspiritech.org')
      cy.title().should('eq', 'Aspiritech – Build it. Break it. Our team tests it. Software QA & Data Services')
      cy.get('.elementor-element-a0fbbb9 > .elementor-widget-container > .elementor-heading-title')
      .contains('Support Our Neurodiverse Team').should('be.visible')
    })
    it('should click through the annual reports by year', () => {
        cy.scrollTo('bottom')
        cy.get('.elementor-element-0fb3afa > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > p').contains('Aspiritech, NFP').should('be.visible')
        cy.contains('a', '2015').click()
        cy.title().should('eq', 'Aspiritech 2015 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'annualreport2015')
        cy.go('back')
        cy.contains('a', '2016').click()
        cy.title().should('eq', 'Aspiritech 2016 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'annualreport2016')
        cy.go('back')
        cy.contains('a', '2017').click()
        cy.title().should('eq', 'Aspiritech 2017 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'annualreport2017')
        cy.go('back')
        cy.contains('a', '2018').click()
        cy.title().should('eq', 'Aspiritech 2018 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'annualreport2018')
        cy.go('back')
        cy.contains('a', '2019').click()
        cy.title().should('eq', 'Aspiritech 2019 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', '2019annualreport')
        cy.go('back')
        cy.contains('a', '2020').click()
        cy.title().should('eq', 'Aspiritech 2020 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'final_2020_annual_report._usable_compressed')
        cy.go('back')
        cy.contains('a', '2021').click()
        cy.title().should('eq', 'Aspiritech 2021 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'aspiritech_2022_update_15_')
        cy.go('back')
        cy.get('[href="https://issuu.com/aspiritech/docs/annual_report_2022_2_"]').click()
        cy.title().should('eq', '2022 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'annual_report_2022_2_')
        cy.go('back')
    })
    it('should click through the rest of the footer links', () => {
        cy.scrollTo('bottom')
        cy.get('.elementor-element-f5e176b > .elementor-widget-container > :nth-child(1) > a').contains('Sitemap').click()
        cy.get('.elementor-4274 > .elementor-section > .elementor-container > .elementor-column > .elementor-widget-wrap').contains('404').should('be.visible')
        cy.title().should('eq', 'Page not found – Aspiritech')
        cy.url().should('include', 'sitemap_index.xml')
        cy.scrollTo('bottom')
        cy.get('.elementor-widget-container > :nth-child(2) > a').contains('Privacy').click()
        cy.get('h1').contains('Privacy Policy').should('be.visible')
        cy.title().should('eq', 'Privacy Policy – Aspiritech')
        cy.url().should('include', 'privacy-policy')
        cy.scrollTo('bottom')
        cy.get('.elementor-widget-container > :nth-child(3) > a').contains('Back to top').click()
    })
})