import Url from "../../support/PageObjects/url"
import Footer from "../../support/PageObjects/footer"
describe('Footer Menu Test', () => {
    let url = new Url()
    let footer = new Footer
    beforeEach(() => {
      url.homePage()
      cy.title().should('eq', 'Aspiritech – Build it. Break it. Our team tests it. Software QA & Data Services')
      cy.get('h3').contains('Support Our Neurodiverse Team').should('be.visible')
    })
    it('should click through the annual reports by year', () => {
        cy.scrollTo('bottom')
        cy.get('div').contains('Aspiritech, NFP').should('be.visible')
        footer.annualReport2015()
        cy.title().should('eq', 'Aspiritech 2015 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'annualreport2015')
        cy.go('back')
        footer.annualReport2016()
        cy.title().should('eq', 'Aspiritech 2016 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'annualreport2016')
        cy.go('back')
        footer.annualReport2017()
        cy.title().should('eq', 'Aspiritech 2017 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'annualreport2017')
        cy.go('back')
        footer.annualReport2018()
        cy.title().should('eq', 'Aspiritech 2018 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'annualreport2018')
        cy.go('back')
        footer.annualReport2019()
        cy.title().should('eq', 'Aspiritech 2019 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', '2019annualreport')
        cy.go('back')
        footer.annualReport2020()
        cy.title().should('eq', 'Aspiritech 2020 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'final_2020_annual_report._usable_compressed')
        cy.go('back')
        footer.annualReport2021()
        cy.title().should('eq', 'Aspiritech 2021 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'aspiritech_2022_update_15_')
        cy.go('back')
        footer.annualReport2022()        
        cy.title().should('eq', '2022 Annual Report by Aspiritech - Issuu')
        cy.url().should('include', 'annual_report_2022_2_')
        cy.go('back')
    })
    it('should click through the rest of the footer links', () => {
        cy.scrollTo('bottom')
        footer.siteMap()
        cy.get('h1').contains('404').should('be.visible')
        cy.title().should('eq', 'Page not found – Aspiritech')
        cy.url().should('include', 'sitemap_index.xml')
        cy.scrollTo('bottom')
        footer.privacy()
        cy.get('h1').contains('Privacy Policy').should('be.visible')
        cy.title().should('eq', 'Privacy Policy – Aspiritech')
        cy.url().should('include', 'privacy-policy')
        cy.scrollTo('bottom')
        footer.backToTop()
    })
})