import Url from "../../../support/PageObjects/url"
import Brokenlinks from "../../../support/PageObjects/brokenlinks"
describe('Software Quality Assurance Page', () => {
    let url = new Url()
    let brokenLinks = new Brokenlinks()
    beforeEach(() => {
        url.sqaPage()
        cy.title().should('eq', 'Software Quality Assurance – Aspiritech')
        cy.get('h1').contains('Software Quality Assurance').should('be.visible')
        cy.url().should('include', 'quality-assurance')
    })
    it('passes', () => {
        cy.get('a.yellow').contains('Book your discovery call now').click()
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        cy.get('h3').contains('Onshore SQA Testing').click({force: true})
        cy.get('h1').contains('Onshore Software Quality Assurance Testing').should('be.visible')
        cy.title().should('eq', 'Onshore Software Quality Assurance Testing – Aspiritech')
        cy.url().should('include', 'quality-assurance/onshore-software-quality-assurance-testing/')
        cy.go('back')
        url.onShore()
        cy.get('div.elementor-widget-container').contains('View all case studies').click()
        cy.get('h1').contains('Case Studies').should('be.visible')
        cy.url().should('include', 'case-studies')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('Bose Case Study').click()
        cy.get('h1').contains('Bose Hardware QA & Product Excellence Case Study').should('be.visible')
        cy.url().should('include', 'bose-case-study')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('Hippo Manager Case Study').click()
        cy.get('h1').contains('Hippo Manager Case Study').should('be.visible')
        cy.url().should('include', 'hippo-manager-case-study')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('HSRI Case Study').click()
        cy.get('h1').contains('HSRI Accessibility Case Study').should('be.visible')
        cy.url().should('include', 'hsri-case-study')
        cy.go('back')
        cy.get('p > .yellow').click()
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
    })
    //brokenLinks.option1()
})