describe('template spec', () => {
  beforeEach(() => {
    cy.visit('https://aspiritech.org')
    cy.title().should('eq', 'Aspiritech – Build it. Break it. Our team tests it. Software QA & Data Services')
    cy.get('.elementor-element-a0fbbb9 > .elementor-widget-container > .elementor-heading-title')
    .contains('Support Our Neurodiverse Team').should('be.visible')
  })
  it('passes', () => {   
    cy.get('.elementor-element-b8ce37c > .elementor-widget-container > p').should('be.visible')
    cy.get('.elementor-element-6dab2e9 > .elementor-widget-container > .elementor-heading-title').contains('Quality Assurance, Accessibility, and Data Services').should('be.visible')
    cy.get('em').contains('Excellence powered by a neurodivergent team')
    cy.get('.elementor-element-62ddefa4 > .elementor-container > .elementor-column > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > h2').contains('Our Services').should('be.visible')
    cy.get('.elementor-element-5a57779f').contains('Accessibility').should('be.visible')
    cy.get('.elementor-element-57c1ddfe > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Accessibility').click()
    cy.url().should('include', 'accessibility')
    cy.get('#aspiritech-logo > .elementor-widget-container > a > .attachment-large').click()
    cy.get('.elementor-element-5a57779f').contains('Audio Testing').should('be.visible')
    cy.get('.elementor-element-6400dffc > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Audio Testing').click()
    cy.url().should('include', 'audio-testing')
    cy.get('#aspiritech-logo > .elementor-widget-container > a > .attachment-large').click()
    cy.get('.elementor-element-5a57779f').contains('Quality Assurance').should('be.visible')
    cy.get('.elementor-element-2d2272a0 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Quality Assurance').click()
    cy.url().should('include', 'quality-assurance')
    cy.get('#aspiritech-logo > .elementor-widget-container > a > .attachment-large').click()
    cy.get('.elementor-element-5a57779f').contains('Data Services').should('be.visible')
    cy.get('.elementor-element-72588606 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Data Services').click()
    cy.url().should('include', 'data-services')
    cy.get('#aspiritech-logo > .elementor-widget-container > a > .attachment-large').click()
    cy.get('.elementor-element-2c0e6c2 > .elementor-widget-container > .elementor-heading-title').contains('Discover how we can help').should('be.visible')
    cy.get('.yellow').contains('Quality Assurance, End-To-End User Testing, and More').click()
    cy.get('.elementor-element-3f7eeaa > .elementor-widget-container > .elementor-heading-title').contains('Software Quality Assurance').should('be.visible')
    cy.url().should('include', 'quality-assurance')
    cy.get('#aspiritech-logo > .elementor-widget-container > a > .attachment-large').click()
    cy.get('.elementor-element-4ecaeb0 > .elementor-widget-wrap').should('be.visible').log('Maunal and Automated Testing', 'Audio Testing', 'Data Integrity and Migration')
    cy.get('.elementor-element-45c70b1 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > h5').contains('All Services').should('be.visible')
    cy.get('.elementor-widget-container > ul').contains('ul', 'Audio Testing').should('be.visible')
    cy.get('.elementor-widget-container > ul > :nth-child(1) > a').click()
    cy.get('.elementor-element-68c0fc70 > .elementor-widget-container > .elementor-heading-title').contains('Audio Testing: Speaker, Headphone & Connectivity Testing').should('be.visible')
    cy.url().should('include', 'audio-testing')
    cy.get('#aspiritech-logo > .elementor-widget-container > a > .attachment-large').click()
    //Getting first 3 article posts on section News & Resources
    cy.get('.elementor-element-48e1f39').then(($article) => {
      cy.wrap($article[0]).should('contain', 'On the Verge Episode 1: The Neurodiversity Employment Landscape with Rebecca Beam')      
      cy.wrap($article[0]).should('contain', 'Welcome to Our Healing Sanctuary Trailer Launch')
      cy.wrap($article[0]).should('contain', 'All The Spectrum Ladies')
    })
    cy.get('.elementor-element-396b2c6 > .elementor-widget-container > .elementor-posts-container > .post-13418 > .elementor-post__text > .elementor-post__title > a').click()  
    cy.get('.elementor-element-aade95e > .elementor-container > .elementor-column > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-heading-title').contains('On the Verge Episode 1: The Neurodiversity Employment Landscape with Rebecca Beam').should('be.visible')
    cy.url().should('include', 'on-the-verge-podcast-episode-1')
    cy.get('#aspiritech-logo > .elementor-widget-container > a > .attachment-large').click()
    
    cy.get('.elementor-element-396b2c6 > .elementor-widget-container > .elementor-posts-container > .post-13202 > .elementor-post__text > .elementor-post__title > a').click()
    cy.get('.elementor-element-5501ef89 > .elementor-widget-container > .elementor-heading-title').contains('Welcome to Our Healing Sanctuary Trailer Launch').should('be.visible')
    cy.url().should('include', 'welcome-to-our-healing-sanctuary-trailer')
    cy.get('#aspiritech-logo > .elementor-widget-container > a > .attachment-large').click()

    cy.get('.elementor-element-396b2c6 > .elementor-widget-container > .elementor-posts-container > .post-13001 > .elementor-post__text > .elementor-post__title > a').click()
    cy.get('.elementor-element-5501ef89 > .elementor-widget-container > .elementor-heading-title').contains('All The Spectrum Ladies').should('be.visible')
    cy.url().should('include', 'all-the-spectrum-ladies')
    cy.get('#aspiritech-logo > .elementor-widget-container > a > .attachment-large').click()
  })
})