import Url from "../../../support/PageObjects/url"
import Brokenlinks from "../../../support/PageObjects/brokenlinks"
describe('template spec', () => {
    let url = new Url()
    let brokenLinks = new Brokenlinks()
    beforeEach(() => {
        url.faqsPage()
        cy.title().should('eq', 'Frequently Asked Questions (FAQs) – Aspiritech')
        cy.get('h1').contains('Frequently Asked Questions (FAQs)').should('be.visible')
        cy.url().should('include', 'faqs')
    })
    it('passes', () => {
        cy.get('h2').contains('General Questions & Answers').should('be.visible')
        cy.get('#elementor-tab-title-4831 > .elementor-accordion-title').contains('Will using Aspiritech take longer than outsourcing to traditional vendors?').should('be.visible')
        cy.get('#elementor-tab-content-4831 > p > span').should('be.visible')
        cy.get('#elementor-tab-title-4832 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-4832 > p > span').should('be.visible')
        cy.get('#elementor-tab-title-4833 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-4833 > p > span')
        cy.get('#elementor-tab-title-4834 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-4834 > p > span')
        cy.get('#elementor-tab-title-4835 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-4835 > p')
        cy.get('#elementor-tab-title-4836 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-4836 > p > span')
        cy.get('#elementor-tab-title-4837 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-4837 > p > span').should('be.visible')

        cy.get('h2').contains('SQA FAQs').should('be.visible')
        cy.get('#elementor-tab-title-1451 > .elementor-accordion-title').contains('What is SQA?').should('be.visible')
        cy.get('#elementor-tab-content-1451 > p > span').should('be.visible')
        cy.get('#elementor-tab-title-1452 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-1452 > ul').should('be.visible')
        cy.get('#elementor-tab-title-1453 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-1453 > p > span').should('be.visible')
        cy.get('#elementor-tab-title-1454 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-1454 > p > span').should('be.visible')
        cy.get('#elementor-tab-title-1455 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-1455 > p > span').should('be.visible')
        cy.get('#elementor-tab-title-1456 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-1456 > p > span').should('be.visible')
        cy.get('#elementor-tab-title-1457 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-1457 > p > span').should('be.visible')

        cy.get('h2').contains('Accessibility FAQs').should('be.visible')
        cy.get('#elementor-tab-title-2551 > .elementor-accordion-title').contains('What is accessibility?').should('be.visible')
        cy.get('#elementor-tab-content-2551 > p').should('be.visible')
        cy.get('#elementor-tab-title-2552 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-2552').should('be.visible')
        cy.get('#elementor-tab-title-2553 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-content-2553').should('be.visible')

    })
    brokenLinks.option1()
})