import Url from "../../support/PageObjects/url"
import Brokenlinks from "../../support/PageObjects/brokenlinks"
describe('News Page', () => {
    let url = new Url()
    let brokenLinks = new Brokenlinks()
    beforeEach(() => {
        url.newsPage()
        cy.title().should('eq', 'News – Aspiritech')
        cy.get('h1').contains('News').should('be.visible')
            })
    it('passes', () => {
        cy.section('Selecting the First 2 Articles')
        cy.get('h2').contains('Recent Posts').should('be.visible')
        cy.get('h3.elementor-post__title').eq(0).contains('a').should('have.attr', 'href', 'https://aspiritech.org/featured/10-ways-businesses-can-leverage-data-ai-for-better-outcomes/').click()
        cy.go('back')
        cy.get('h3.elementor-post__title').eq(1).contains('a').should('have.attr', 'href', 'https://aspiritech.org/featured/board-member-spotlight-brad-zelinger-founder-and-ceo-of-stride-autism-centers/').click()
        cy.go('back')
        cy.section('Page Numbers')
        cy.get('nav.elementor-pagination').url().should('include', 'news')
        cy.get('a.page-numbers').should('have.attr', 'href', 'https://aspiritech.org/category/news/page/2/').contains('2').click()
        cy.title().should('eq', 'News – Page 2 – Aspiritech')
        cy.get('nav.elementor-pagination').url().should('include', '2')
        cy.get('a.page-numbers').should('have.attr', 'href', 'https://aspiritech.org/category/news/').contains('3').click()
        cy.title().should('eq', 'News – Page 3 – Aspiritech')
        cy.get('nav.elementor-pagination').url().should('include', '3')
        cy.get('a.page-numbers').should('have.attr', 'href', 'https://aspiritech.org/category/news/').contains('4').click()
        cy.title().should('eq', 'News – Page 4 – Aspiritech')
        cy.get('nav.elementor-pagination').url().should('include', '4')
        cy.get('a.page-numbers').should('have.attr', 'href', 'https://aspiritech.org/category/news/').contains('5').click()
        cy.title().should('eq', 'News – Page 5 – Aspiritech')
        cy.get('nav.elementor-pagination').url().should('include', '5')

        cy.section('More Topics & Categories')
        cy.get('h2').contains('More Topics & Categories').should('be.visible')
        cy.get('#form-field-topicselect').select('News', {force: true}).invoke("val").should("eq", "news")
        cy.get('#button-primary').contains('Go to topic').click()
        cy.title().should('eq', 'News & Resources – Aspiritech')
        cy.url().should('include', 'news')
        cy.wait(3000)
        cy.get('#form-field-topicselect').select('In the Press', {force: true}).invoke("val").should("eq", "press")
        cy.get('#button-primary').contains('Go to topic').click()
        cy.wait(3000)
        cy.title().should('eq', 'In the Press – Aspiritech')
        cy.url().should('include', 'press')
        cy.get('#form-field-topicselect').select('Events', {force: true}).invoke("val").should("eq", "events")
        cy.get('#button-primary').contains('Go to topic').click()
        cy.title().should('eq', 'Events – Aspiritech')
        cy.url().should('include', 'events')
        cy.go('back')
        cy.get('#form-field-topicselect').select('Stepping Up and Out', {force: true}).invoke("val").should("eq", "stepping-up")
        cy.get('#button-primary').contains('Go to topic').click()
        cy.title().should('eq', 'Stepping Up & Out – Aspiritech')
        cy.url().should('include', 'stepping-up')
        cy.get('#form-field-topicselect').select('Neurodiversity Resource Library', {force: true}).invoke("val").should("eq", "neurodiversity-resource-library")
        cy.get('#button-primary').contains('Go to topic').click()
        cy.title().should('eq', 'Neurodiversity Resource Library – Aspiritech')
        cy.url().should('include', 'neurodiversity-resource-library')
        })
        brokenLinks.option1()
    })
