describe('template spec', () => {
    beforeEach(() => {
        cy.visit('https://aspiritech.org/category/news/')
        cy.title().should('eq', 'News – Aspiritech')
        cy.get('.elementor-element-450440ca > .elementor-widget-container > .elementor-heading-title').contains('News').should('be.visible')
            })
    it('passes', () => {
        cy.section('Selecting the First 2 Articles')
        cy.get('.elementor-element-b24796 > .elementor-widget-container > .elementor-heading-title').contains('Recent Posts').should('be.visible')
        cy.get('.elementor-post__title').eq(0).contains('a').click()
        cy.go('back')
        cy.get('.elementor-post__title').eq(1).contains('a').click()
        cy.go('back')
        cy.section('Page Numbers')
        cy.get('.elementor-element-19068368 > .elementor-widget-container > .elementor-pagination > .current').url().should('include', 'news')
        cy.get('.elementor-element-19068368 > .elementor-widget-container > .elementor-pagination > [href="https://aspiritech.org/category/news/page/2/"]').contains('2').click()
        cy.title().should('eq', 'News – Page 2 – Aspiritech')
        cy.get('.current').url().should('include', '2')
        cy.get('.elementor-element-19068368 > .elementor-widget-container > .elementor-pagination > [href="https://aspiritech.org/category/news/page/3/"]').contains('3').click()
        cy.title().should('eq', 'News – Page 3 – Aspiritech')
        cy.get('.current').url().should('include', '3')
        cy.get('.elementor-element-19068368 > .elementor-widget-container > .elementor-pagination > [href="https://aspiritech.org/category/news/page/4/"]').contains('4').click()
        cy.title().should('eq', 'News – Page 4 – Aspiritech')
        cy.get('.current').url().should('include', '4')
        cy.get('.elementor-element-19068368 > .elementor-widget-container > .elementor-pagination > [href="https://aspiritech.org/category/news/page/5/"]').contains('5').click()
        cy.title().should('eq', 'News – Page 5 – Aspiritech')
        cy.get('.current').url().should('include', '5')

        cy.section('More Topics & Categories')
        cy.get('.elementor-element-31aca0b6 > .elementor-widget-container > .elementor-heading-title').contains('More Topics & Categories').should('be.visible')
        cy.get('#form-field-topicselect').select('News', {force: true}).invoke("val").should("eq", "news")
        cy.get('#button-primary').contains('Go to topic').click()
        cy.title().should('eq', 'News & Resources – Aspiritech')
        cy.url().should('include', 'news')
        cy.wait(3000)
        cy.get('#form-field-topicselect').select('In the Press', {force: true}).invoke("val").should("eq", "press")
        cy.get('#button-primary').contains('Go to topic').click()
        cy.wait(3000)
        cy.title().should('eq', 'In the Press – Aspiritech')
        cy.url().should('include', 'press')
        cy.get('#form-field-topicselect').select('Events', {force: true}).invoke("val").should("eq", "events")
        cy.get('#button-primary').contains('Go to topic').click()
        cy.title().should('eq', 'Events – Aspiritech')
        cy.url().should('include', 'events')
        cy.go('back')
        cy.get('#form-field-topicselect').select('Stepping Up and Out', {force: true}).invoke("val").should("eq", "stepping-up")
        cy.get('#button-primary').contains('Go to topic').click()
        cy.title().should('eq', 'Stepping Up & Out – Aspiritech')
        cy.url().should('include', 'stepping-up')
        cy.get('#form-field-topicselect').select('Neurodiversity Resource Library', {force: true}).invoke("val").should("eq", "neurodiversity-resource-library")
        cy.get('#button-primary').contains('Go to topic').click()
        cy.title().should('eq', 'Neurodiversity Resource Library – Aspiritech')
        cy.url().should('include', 'neurodiversity-resource-library')
        })
        it('Finds all broken links', () => {
            cy.get('a').each(link => {
                if (link.prop('href'))
                    cy.request({
                        url: link.prop('href'),
                        failOnStatusCode: false
                    })
                cy.log(link.prop('href'))
            })
        })
    })
