import Url from "../../support/PageObjects/url"
import Brokenlinks from "../../support/PageObjects/brokenlinks"
describe('On the Verge Podcast Page', () => {
    let url = new Url()
    let brokenLinks = new Brokenlinks()
    beforeEach(() => {
        url.podcastPage()
        cy.title().should('eq', 'On the Verge Podcast – Aspiritech')
        cy.get('h2').contains('On the Verge: Conversations with the Neurodiversity Movement').should('be.visible')
    })
    it('The user gets directed to Spotify to listen to podcast', () => {
        cy.get('.elementor-element-ccee8e2 > .elementor-widget-container > .elementor-heading-title').contains('Latest Episodes').should('be.visible')
        url.spotifyUrl()
        cy.get('[data-testid="showTitle"]').contains('On the Verge').should('be.visible')
        cy.title().should('eq', 'On the Verge | Podcast on Spotify')
        cy.url().should('include', 'show')
        cy.go('back')
    })
    it('The user gets directed to Apple Podcasts to listen to podcast', () => {
        url.appleUrl()
        cy.get('.product-header__title').contains('On the Verge').should('be.visible')
        cy.title().should('eq', 'On the Verge on Apple Podcasts')
        cy.url().should('include', 'podcast')
        cy.go('back')
    })
    it('The user gets directed to iHeart Radio to listen to podcast', () => {
        url.iHeartUrl()
        cy.get('[data-test="podcast-profile-heading"]').contains('On the Verge').should('be.visible')
        cy.title().should('eq', 'On the Verge | iHeart')
        cy.url().should('include', 'podcast')
        cy.go('back')
    })
    it('The user gets directed to Amazon Music to listen to podcast', () => {
        url.amazonUrl()
        //cy.get('div.secondaryHeadline').contains('On the Verge').should('be.visible')
        cy.title().should('eq', 'On the Verge Podcast on Amazon Music')
        cy.url().should('include', 'podcasts')
        cy.go('back')
    })
    it('The user gets directed to YouTube to listen to podcast', () => {
        url.youTubeUrl()
        cy.get('.metadata-wrapper > :nth-child(1) > #container > #text').contains('On the Verge').should('be.visible')
        cy.title().should('eq', 'On the Verge: Conversations with the Neurodiversity Movement - Presented by Aspiritech - YouTube')
        cy.url().should('include', 'playlist')
        cy.go('back')
    })
    it('User selects link, plays a podcast video and views video transcript', () => {
        cy.get('.elementor-element-eaabc5b > .elementor-widget-container > p > a').contains('Watch the episode video and read the transcript. »').click()
        cy.get('h1').contains('Episode 3').should('be.visible')
        cy.title().should('eq', 'On the Verge Episode 3: Autistic Representation with Scott Steindorff – Aspiritech')
        cy.url().should('include', 'episode-3')
        cy.get('h2 > span').contains('Episode Transcript').should('be.visible')
        cy.go('back')
        cy.get('.elementor-element-43bd676 > .elementor-widget-container > p > a').contains('Watch the episode video and view the transcript. »').click()
        cy.get('h1').contains('Episode 2').should('be.visible')
        cy.title().should('eq', 'On the Verge Episode 2: Sensory Gated Art with Amanda Hebert Hughes – Aspiritech')
        cy.url().should('include', 'episode-2')
        cy.get('h2 > span').contains('Episode Transcript').should('be.visible')
        cy.go('back')
        cy.get('.elementor-element-49fa451 > .elementor-widget-container > p > a').contains('Watch the episode video and view the transcript. »').click()
        cy.get('h1').contains('Episode 1').should('be.visible')
        cy.title().should('eq', 'On the Verge Episode 1: The Neurodiversity Employment Landscape with Rebecca Beam – Aspiritech')
        cy.url().should('include', 'episode-1')
        cy.get('h2 > span').contains('Episode Transcript').should('be.visible')
        cy.go('back')
    })
    brokenLinks.option1()
})

