import Url from "../../support/PageObjects/url"
import Brokenlinks from "../../support/PageObjects/brokenlinks"
describe('SUO Program Page', () => {
    let url = new Url()
    let brokenLinks = new Brokenlinks()
    beforeEach(() => {
        url.suoprogramPage()
        cy.title().should('eq', 'About the Stepping Up & Out (SUO) Program – Aspiritech')
        cy.get('h1').contains('About the Stepping Up & Out (SUO) Program').should('be.visible')
        })
    it('passes', () => {
        cy.get('h3').contains('Team photos from our SUO events').should('be.visible')
        url.photo1Url()
        cy.get('.dialog-close-button > .eicon-close').click()
        url.photo2Url()
        cy.get('.dialog-close-button > .eicon-close').click()
        url.photo3Url()
        cy.get('.dialog-close-button > .eicon-close').click()
        cy.get('h3').contains('Benefits and Activities of the SUO Program').should('be.visible')
        cy.get('h3').contains('To Participate in Aspiritech’s Stepping Up & Out').should('be.visible')
        cy.get('a').contains('charitable donation').click()
        cy.get('h1').contains('Support Our Mission').should('be.visible')
        cy.title().should('eq', 'Support Our Mission – Aspiritech')
        cy.url().should('include', 'support-our-mission')
        cy.go('back')
        cy.get('span').contains('software testing specialists').should('be.visible')
        cy.get('.underline').contains('Contact us').click()
        cy.title().should('eq', 'Contact Us – Aspiritech')
        cy.url().should('include', 'contact-us')
        cy.get('span').contains('Contact us').should('be.visible')
        cy.go('back')
        cy.get('a.elementor-button').contains('Services we offer').click()
        cy.title().should('eq', 'Services – Aspiritech')
        cy.get('h1').contains('Services').should('be.visible')
        cy.url().should('include', 'services')
        cy.go('back')
        cy.get('span > a').contains('About Aspiritech').click()
        cy.title().should('eq', 'About Us – Aspiritech')
        cy.get('h1').contains('About Us').should('be.visible')   
        cy.url().should('include', 'about-us')
        cy.go('back')
    })
        brokenLinks.option1()
    })
