describe('template spec', () => {
    beforeEach(() => {
        cy.visit('https://aspiritech.org/featured/about-the-stepping-up-out-suo-program/')
        cy.title().should('eq', 'About the Stepping Up & Out (SUO) Program – Aspiritech')
        cy.get('h1').contains('About the Stepping Up & Out (SUO) Program').should('be.visible')
        })
    it('passes', () => {
        cy.get('h3').contains('Team photos from our SUO events').should('be.visible')
        cy.get('[href="https://aspiritech.org/wp-content/uploads/2022/11/SUO-stepping-up-out-team-photo02-martial-arts.jpg"] > .elementor-gallery-item__content').click()
        cy.get('.dialog-close-button > .eicon-close').click()
        cy.get('[href="https://aspiritech.org/wp-content/uploads/2022/11/SUO-stepping-up-out-team-photo35-PacMan.jpg"] > .elementor-gallery-item__content').click()
        cy.get('.dialog-close-button > .eicon-close').click()
        cy.get('[href="https://aspiritech.org/wp-content/uploads/2022/11/SUO-stepping-up-out-team-photo36-O-Neils-Wells-Feb-21-2020.jpg"] > .elementor-gallery-item__content')
        cy.get('.dialog-close-button > .eicon-close').click()
        cy.get('h3').contains('Benefits and Activities of the SUO Program').should('be.visible')
        cy.get('h3').contains('To Participate in Aspiritech’s Stepping Up & Out').should('be.visible')
        cy.get('a').contains('charitable donation').click()
        cy.get('h1').contains('Support Our Mission').should('be.visible')
        cy.title().should('eq', 'Support Our Mission – Aspiritech')
        cy.url().should('include', 'support-our-mission')
        cy.go('back')
        cy.get('span').contains('software testing specialists').should('be.visible')
        cy.get('.underline').contains('Contact us').click()
        cy.title().should('eq', 'Contact Us – Aspiritech')
        cy.url().should('include', 'contact-us')
        cy.get('span').contains('Contact us').should('be.visible')
        cy.go('back')
        cy.get('a.elementor-button').contains('Services we offer').click()
        cy.title().should('eq', 'Services – Aspiritech')
        cy.get('h1').contains('Services').should('be.visible')
        cy.url().should('include', 'services')
        cy.go('back')
        cy.get('span > a').contains('About Aspiritech').click()
        cy.title().should('eq', 'About Us – Aspiritech')
        cy.get('h1').contains('About Us').should('be.visible')   
        cy.url().should('include', 'about-us')
        cy.go('back')
    })
        it('Finds all broken links', () => {
            cy.get('a').each(link => {
                if (link.prop('href'))
                    cy.request({
                        url: link.prop('href'),
                        failOnStatusCode: false
                    })
                cy.log(link.prop('href'))
            })
        })
    })
