import Url from "../../support/PageObjects/url"
import Brokenlinks from "../../support/PageObjects/brokenlinks"
describe('template spec', () => {
    let url = new Url()
    let brokenLinks = new Brokenlinks()
    beforeEach(() => {
        url.aboutusPage()
        cy.title().should('eq', 'About Us – Aspiritech')
        cy.get('h1').contains('About Us').should('be.visible')   
        })
    it('passes', () => {
        cy.section('Services')
        cy.get('h4').contains('Accessibility').should('be.visible')
        cy.get('div.elementor-element-7c3a460 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__button-wrapper > .elementor-cta__button').click()
        cy.title().should('eq', 'Accessibility Testing: Design, UX, Usability, & WCAG Conformance – Aspiritech')
        cy.url().should('include', 'accessibility')   
        cy.get('h1').contains('Accessibility Testing: Design, UX, Usability, & WCAG Conformance').should('be.visible')
        cy.go('back')
        cy.get('h4').contains('Audio Testing').should('be.visible')
        cy.get('div.elementor-element-c0d79ec > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__button-wrapper > .elementor-cta__button').click()
        cy.title().should('eq', 'Audio & Hardware Testing: Speakers, Headphones, & Connectivity – Aspiritech')
        cy.url().should('include', 'audio-testing')
        cy.get('h1').contains('Audio & Hardware Testing: Speakers, Headphones, & Connectivity').should('be.visible')
        cy.go('back')
        cy.get('h4').contains('Software QA').should('be.visible')
        cy.get('div.elementor-element-fcdb2f8 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__button-wrapper > .elementor-cta__button').click()
        cy.title().should('eq', 'Software Quality Assurance – Aspiritech')
        cy.get('h1').contains('Software Quality Assurance').should('be.visible')
        cy.url().should('include', 'quality-assurance')
        cy.go('back')
        cy.get('h4').contains('Data Services').should('be.visible')
        cy.get('div.elementor-element-890bb2c > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__button-wrapper > .elementor-cta__button').click()
        cy.title().should('eq', 'Data Services: Data Annotation, Data Labeling, and Data Validation. – Aspiritech')
        cy.url().should('include', 'data-services')
        cy.get('h1').contains('Data Services: Data Annotation, Data Labeling, and Data Validation.').should('be.visible')
        cy.go('back')
        cy.get('h2').contains('NeuroGrowth Training Services').should('be.visible')
        cy.get('div.elementor-element-cfd7392 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__button-wrapper > .elementor-cta__button').click()
        cy.get('h1').contains('NeuroGrowth Training Services').should('be.visible')
        cy.title().should('eq', 'NeuroGrowth Training Services: You already have a neurodiverse team – Aspiritech')
        cy.url().should('include', 'neurogrowth-training-services-for-companies-and-organizations')
        cy.go('back')
        cy.section('Training Academy')
        cy.get('h2').contains('Training Academy').should('be.visible')
        url.mitsubishiLink2()
        cy.title().should('eq', 'Mitsubishi Electric America Foundation | Greater Community | Sustainability | MITSUBISHI ELECTRIC UNITED STATES')
        cy.url().should('include', 'index')
        cy.go('back')
        url.haapeLink()
        cy.title().should('eq', 'HAAPE - Helping Adults with Autism Perform and Excel')
        cy.url().should('eq', 'https://haape.org/')
        cy.go('back')
        cy.get('p > a').contains('visit the Aspiritech Academy page').click()
        cy.get('h1').contains('Aspiritech Academy').should('be.visible')
        cy.title().should('eq', 'Aspiritech Academy – Aspiritech')
        cy.url().should('include', 'aspiritech-academy')
        cy.go('back')
        cy.section('Leadership Team')
        cy.get('h2').contains('Leadership Team').should('be.visible')
        cy.get('a.elementor-button').contains('Read full bios').click()
        cy.get('h1').contains('Leadership').should('be.visible')
        cy.title().should('eq', 'Leadership – Aspiritech')
        cy.url().should('include', 'leadership')
        cy.go('back')    
        })
        brokenLinks.option1()
    })
