describe('template spec', () => {
    beforeEach(() => {
        cy.visit('https://aspiritech.org/services/about-us/')
        cy.title().should('eq', 'About Us – Aspiritech')
        cy.get('.elementor-element-78885b1 > .elementor-widget-container > .elementor-heading-title').contains('About Us').should('be.visible')   
        })
    it('passes', () => {
        cy.section('Services')
        cy.get('.elementor-element-7c3a460 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content').contains('Accessibility').should('be.visible')
        cy.get('.elementor-element-7c3a460 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__button-wrapper > .elementor-cta__button').click()
        cy.title().should('eq', 'Accessibility Testing: Design, UX, Usability, & WCAG Conformance – Aspiritech')
        cy.url().should('include', 'accessibility')   
        cy.get('.elementor-element-4fb348f1 > .elementor-widget-container > .elementor-heading-title').contains('Accessibility Testing: Design, UX, Usability, & WCAG Conformance').should('be.visible')
        cy.go('back')
        cy.get('.elementor-element-c0d79ec > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content').contains('Audio Testing').should('be.visible')
        cy.get('.elementor-element-c0d79ec > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__button-wrapper > .elementor-cta__button').click()
        cy.title().should('eq', 'Audio & Hardware Testing: Speakers, Headphones, & Connectivity – Aspiritech')
        cy.url().should('include', 'audio-testing')
        cy.get('.elementor-element-68c0fc70 > .elementor-widget-container > .elementor-heading-title').contains('Audio & Hardware Testing: Speakers, Headphones, & Connectivity').should('be.visible')
        cy.go('back')
        cy.get('.elementor-element-fcdb2f8 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content').contains('Software QA').should('be.visible')
        cy.get('.elementor-element-fcdb2f8 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__button-wrapper > .elementor-cta__button').click()
        cy.title().should('eq', 'Software Quality Assurance – Aspiritech')
        cy.get('.elementor-element-3f7eeaa > .elementor-widget-container > .elementor-heading-title').contains('Software Quality Assurance').should('be.visible')
        cy.url().should('include', 'quality-assurance')
        cy.go('back')
        cy.get('.elementor-element-890bb2c > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content').contains('Data Services').should('be.visible')
        cy.get('.elementor-element-890bb2c > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__button-wrapper > .elementor-cta__button').click()
        cy.title().should('eq', 'Data Services: Data Annotation, Data Labeling, and Data Validation. – Aspiritech')
        cy.url().should('include', 'data-services')
        cy.get('.elementor-element-63b8939c > .elementor-widget-container > .elementor-heading-title').contains('Data Services: Data Annotation, Data Labeling, and Data Validation.').should('be.visible')
        cy.go('back')
        cy.get('.elementor-element-cfd7392 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__title').contains('NeuroGrowth Training Services').should('be.visible')
        cy.get('.elementor-element-cfd7392 > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-cta > .elementor-cta__content > .elementor-cta__button-wrapper > .elementor-cta__button').click()
        cy.get('.elementor-element-8a02e95 > .elementor-widget-container > .elementor-heading-title').contains('NeuroGrowth Training Services').should('be.visible')
        cy.title().should('eq', 'NeuroGrowth Training Services: You already have a neurodiverse team – Aspiritech')
        cy.url().should('include', 'neurogrowth-training-services-for-companies-and-organizations')
        cy.go('back')
        cy.section('Training Academy')
        cy.get('.elementor-element-1b21bc2 > .elementor-widget-container > .elementor-heading-title').contains('Training Academy').should('be.visible')
        cy.get('[href="https://us.mitsubishielectric.com/en/sustainability/greater-community/meaf-top/index.html"]').contains('Mitsubishi Electric America Foundation').click()
        cy.title().should('eq', 'Mitsubishi Electric America Foundation | Greater Community | Sustainability | MITSUBISHI ELECTRIC UNITED STATES')
        cy.url().should('include', 'index')
        cy.go('back')
        cy.get('[href="https://haape.org/"]').contains('HAAPE').click()
        cy.title().should('eq', 'HAAPE FOUNDATION')
        cy.url().should('eq', 'https://haape.org/')
        cy.go('back')
        cy.get('.elementor-widget-container > :nth-child(6) > a').contains('visit the Aspiritech Academy page').click()
        cy.get('.elementor-element-68c0fc70 > .elementor-widget-container > .elementor-heading-title').contains('Aspiritech Academy').should('be.visible')
        cy.title().should('eq', 'Aspiritech Academy – Aspiritech')
        cy.url().should('include', 'aspiritech-academy')
        cy.go('back')
        cy.section('Leadership Team')
        cy.get('.elementor-element-ef8bcc0 > .elementor-widget-container > .elementor-heading-title').contains('Leadership Team').should('be.visible')
        cy.get('.elementor-element-d5a7fb1 > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Read full bios').click()
        cy.get('.elementor-element-9ce7074 > .elementor-widget-container > .elementor-heading-title').contains('Leadership').should('be.visible')
        cy.title().should('eq', 'Leadership – Aspiritech')
        cy.url().should('include', 'leadership')
        cy.go('back')    
        })
        
    })
