describe('template spec', () => {
    beforeEach(() => {
        cy.visit('https://aspiritech.org/services/careers/')
        cy.title().should('eq', 'Careers – Aspiritech')
        cy.get('h1').contains('Careers').should('be.visible')   
        })
    it('passes', () => {
        cy.get('h2').contains('Employment opportunities at Aspiritech').should('be.visible')
        cy.get('a.elementor-button').contains('Apply now').click()
        cy.title().should('eq', 'Aspiritech NFP - Job Opportunities')
        cy.url().should('include', 'Aspiritech-NFP')
        cy.get('#LayoutLogoName').contains('Aspiritech NFP').should('be.visible')
        cy.go('back')
        cy.get('#hs-form-iframe-0')
        cy.get('h2').contains('Aspiritech Careers: FAQ').should('be.visible')
        cy.get('#elementor-tab-title-2531 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-title-2532 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-title-2533 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-title-2534 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-title-2535 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-title-2536 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-title-2537 > .elementor-accordion-title').click()
        cy.get('#elementor-tab-title-2538 > .elementor-accordion-title').click()
        cy.get('h2 > span').contains('benefits').should('be.visible')
        cy.get('h2').contains('Social Programs').should('be.visible')
        cy.get('[href="mailto:SUO@aspiritech.org"] > span')
        cy.get('p > :nth-child(3) > a').contains('SUO page of our website').click()
        cy.title().should('eq', 'About the Stepping Up & Out (SUO) Program – Aspiritech')
        cy.url().should('include', 'about-the-stepping-up-out-suo-program')
        cy.get('h1').contains('About the Stepping Up & Out (SUO) Program').should('be.visible')
        cy.go('back')
        cy.get('h2 > a').click()
        cy.title().should('eq', 'Team Members – Aspiritech')
        cy.url().should('include', 'team-members')
        cy.get('h1').contains('Team Members').should('be.visible')
        cy.go('back')
        })
        it('Finds all broken links', () => {
            cy.get('a').each(link => {
                if (link.prop('href'))
                    cy.request({
                        url: link.prop('href'),
                        failOnStatusCode: false
                    })
                cy.log(link.prop('href'))
            })
        })
    })
