import Url from "../../support/PageObjects/url"
import Brokenlinks from "../../support/PageObjects/brokenlinks"
describe('Support Our Mission Page', () => {
    let url = new Url()
    let brokenLinks = new Brokenlinks()
    beforeEach(() => {
        url.supportourmissionPage()
        cy.title().should('eq', 'Support Our Mission – Aspiritech')
        cy.get('h1').contains('Support Our Mission').should('be.visible')
        
        })
    it('passes', () => {
        cy.get('a.elementor-button').contains('Donate now').click()
        cy.get('h2').contains('Other Ways to Donate').should('be.visible')
        cy.get('p').contains('Text to Donate:').should('be.visible')
        cy.get('p').contains('Mail your donation').should('be.visible')
        cy.get('p').contains('Buy Aspiritech Merchandise').should('be.visible')
        cy.get('a.elementor-button').contains('Shop Now').click()
        cy.get('span').contains('Aspiritech Gifts & Apparel').should('be.visible')
        cy.title().should('eq', 'Aspiritech Gifts & Apparel | Support Our Mission | Bonfire')
        cy.url().should('include', 'aspiritech-merch')
        cy.go('back')
        cy.get('p').contains('Create a Lasting Legacy').should('be.visible')
        cy.get('a.elementor-button').contains('Donor Confidentiality and Privacy Policy').click()
        cy.go('back')
        cy.get('h2').contains('Support Aspiritech!')
        url.termsLink()
        cy.title().should('eq', 'Terms Of Use | Give Lively')
        cy.url().should('include', 'terms-of-use')
        cy.get('h1').contains('Terms Of Use').should('be.visible')
        cy.go('back')
        url.privacyLink()
        cy.title().should('eq', 'Privacy Policy | Give Lively')
        cy.url().should('include', 'privacy-policy')
        cy.get('h1').contains('Privacy Policy').should('be.visible')
        cy.go('back')
        url.giveLively()
        })
        brokenLinks.option1()
    })
