describe('template spec', () => {
  beforeEach(() => {
    cy.visit('https://aspiritech.org')
    cy.title().should('eq', 'Aspiritech – Build it. Break it. Our team tests it. Software QA & Data Services')
    cy.get('h3').contains('Support Our Neurodiverse Team').should('be.visible')
  })
  it('passes', () => {
    cy.get('h2').contains('Quality Assurance, Accessibility, and Data Services').should('be.visible')
    cy.get('em').contains('Excellence powered by a neurodivergent team')
    cy.get('h2').contains('Our Services').should('be.visible')
    cy.get('.elementor-element-5a57779f').contains('Accessibility').should('be.visible')
    cy.get('.elementor-button').contains('a', 'Accessibility').should('have.attr', 'href', '/services/accessibility/').click()
    cy.get('h1').contains('Accessibility Testing: Design, UX, Usability, & WCAG Conformance').should('be.visible')
    cy.title().should('eq', 'Accessibility Testing: Design, UX, Usability, & WCAG Conformance – Aspiritech')
    cy.url().should('include', 'accessibility')
    cy.go('back')
    cy.get('.elementor-element-5a57779f').contains('Audio Testing').should('be.visible')
    cy.get('.elementor-button').should('have.attr', 'href', '/contact-us/').contains('a', 'Audio Testing').click()
    cy.get('h1').contains('Audio & Hardware Testing: Speakers, Headphones, & Connectivity').should('be.visible')
    cy.title().should('eq', 'Audio & Hardware Testing: Speakers, Headphones, & Connectivity – Aspiritech')
    cy.url().should('include', 'audio-testing')
    cy.go('back')
    cy.get('.elementor-element-5a57779f').contains('Quality Assurance').should('be.visible')
    cy.get('.elementor-button').should('have.attr', 'href', '/contact-us/').contains('Quality Assurance').click()
    cy.get('h1').contains('Software Quality Assurance')
    cy.title().should('eq', 'Software Quality Assurance – Aspiritech')
    cy.url().should('include', 'quality-assurance')
    cy.go('back')
    cy.get('.elementor-element-5a57779f').contains('Data Services').should('be.visible')
    cy.get('.elementor-button').should('have.attr', 'href', '/contact-us/').contains('Data Services').click()
    cy.get('h1').contains('Data Services: Data Annotation, Data Labeling, and Data Validation.').should('be.visible')
    cy.title().should('eq', 'Data Services: Data Annotation, Data Labeling, and Data Validation. – Aspiritech')
    cy.url().should('include', 'data-services')
    cy.go('back')
    cy.get('.elementor-element-2c0e6c2 > .elementor-widget-container > .elementor-heading-title').contains('Discover how we can help').should('be.visible')
    cy.get('.yellow').contains('Quality Assurance, End-To-End User Testing, and More').should('have.attr', 'href', '/index.php/services/quality-assurance/').click()
    cy.get('h1').contains('Software Quality Assurance').should('be.visible')
    cy.url().should('include', 'quality-assurance')
    cy.go('back')
    cy.get('.elementor-element-4ecaeb0 > .elementor-widget-wrap').should('be.visible').log('Maunal and Automated Testing', 'Audio Testing', 'Data Integrity and Migration')
    cy.get('h5').contains('All Services').should('be.visible')
    cy.get('.elementor-widget-container > ul').contains('ul', 'Audio Testing').should('be.visible')
    cy.get('.elementor-widget-container > ul > :nth-child(1) > a').click()
    cy.get('h1').contains('Audio & Hardware Testing: Speakers, Headphones, & Connectivity').should('be.visible')
    cy.url().should('include', 'audio-testing')
    cy.go('back')
    cy.get('h2').contains('Our Expertise').should('be.visible')
    cy.get('.elementor-button').contains('a', 'Services').should('have.attr', 'href', '/services/data-services/').click()
    cy.title().should('eq', 'Data Services: Data Annotation, Data Labeling, and Data Validation. – Aspiritech')
    cy.get('h1').contains('Data Services: Data Annotation, Data Labeling, and Data Validation.').should('be.visible')
    cy.url().should('include', 'data-services')
    cy.go('back')
    cy.get('h2').contains('Our Team').should('be.visible')
    cy.get('.elementor-button').contains('a', 'About Aspiritech').should('have.attr', 'href', '/about-us/').click()
    cy.title().should('eq', 'About Us – Aspiritech')
    cy.url().should('include', 'about-us')
    cy.get('.elementor-element-78885b1 > .elementor-widget-container > .elementor-heading-title').contains('About Us').should('be.visible')
    cy.go('back')   
    cy.get('h2').contains('Our Philosophy').should('be.visible')
    cy.get('.elementor-button').contains('a', 'Our story').should('have.attr', 'href', '/our-story/').click()
    cy.title().should('eq', 'Our Story – Aspiritech')
    cy.url().should('include', 'our-story')
    cy.get('.elementor-element-af53a48 > .elementor-widget-container > .elementor-heading-title').contains('Our Story').should('be.visible')
    cy.go('back')
    //check for the column div
    cy.get('div[data-id="bfa597f"]').should('be.visible')
    //check for the video widget div
    cy.get('.elementor-element-1e614d4').should('be.visible')
    //check for the video iframe
    cy.get('.elementor-element-1e614d4 .elementor-video-iframe').should('be.visible').and('have.attr', 'data-src',
      'https://www.youtube.com/embed/kCgARx7JYdY?feature=oembed&color&autopause=0&loop=0&muted=0&title=1&portrait=1&byline=1').as('iframeBody')
    //load the page and wait for the iframe to load
    //cy.frameLoaded('.elementor-element-1e614d4 .elementor-video-iframe')
    //cy.iframe().find('body').as('iframeBody')
    //play the video
    // cy.get('@iframeBody').find('.elementor-element-1e614d4 .elementor-video-iframe').then(($video) => {
    //   $video[0].play()
    // })
    // cy.wait(10000)
    // cy.get('@iframeBody').find('video').then(($video) => {
    //   $video[0].pause()
    // })
    //Getting first 3 article posts on section News & Resources
    cy.get('h2').contains('News & Resources').should('be.visible')
    cy.get('.elementor-element-48e1f39').then(($article) => {
      cy.wrap($article[0]).should('contain', 'Help Us Build a Virtual Cookbook')
      cy.wrap($article[0]).should('contain', 'On the Verge Episode 2: Sensory Gated Art with Amanda Hebert Hughes')
      cy.wrap($article[0]).should('contain', 'Mitsubishi Electric America Foundation Announces $2 Million in New Grants')
    })

  })
})