import Home from "../../support/PageObjects/home"
import Url from "../../support/PageObjects/url"
describe('Home page', () => {
  let home = new Home()
  let url = new Url()
  beforeEach(() => {
    url.homePage()
    cy.title().should('eq', 'Welcome to Aspiritech » Aspiritech Neurodivergent QA Testers')
    cy.get('h3').contains('Cultivate Potential for Autistic Adults').should('be.visible')
  })
  it('Tests the home page', () => {
    // cy.get('h2').contains('Quality Assurance, Accessibility, and Data Services').should('be.visible')
    // cy.get('em').contains('Excellence powered by a neurodivergent team')
    // cy.get('h2').contains('Our Services').should('be.visible')
    // home.accessibility().contains('a', 'Accessibility').should('have.attr', 'href', '/services/accessibility/').click()
    // cy.get('h1').contains('Accessibilit').should('be.visible')
    // cy.title().should('eq', 'Accessibility Testing: Design, Usability, & WCAG Conformance » Aspiritech')
    // cy.url().should('include', 'accessibility')
    // cy.go('back')
    // home.audioTesting().should('have.attr', 'href', '/services/audio-testing/').contains('a', 'Audio Testing').click()
    // cy.get('h1').contains('Audio & Hardware Testing: Speakers, Headphones, & Connectivity').should('be.visible')
    // cy.title().should('eq', 'Audio & Hardware Testing: Speakers, Headphones, & Connectivity » Aspiritech')
    // cy.url().should('include', 'audio-testing')
    // cy.go('back')
    // home.qualityAssurance().should('have.attr', 'href', '/services/quality-assurance/').contains('Quality Assurance').click()
    // cy.get('h1').contains('Software Quality Assurance')
    // cy.title().should('eq', 'Software Quality Assurance » Aspiritech')
    // cy.url().should('include', 'quality-assurance')
    // cy.go('back')
    // home.dataServices().should('have.attr', 'href', '/services/data-services/').contains('Data Services').click()
    // cy.get('h1').contains('Data Services').should('be.visible')
    // cy.title().should('eq', 'Data Services: Data Annotation, Data Labeling, and Data Validation » Aspiritech')
    // cy.url().should('include', 'data-services')
    // cy.go('back')
    // home.creativeServices().should('have.attr', 'href', '/services/creative-services/').contains('Creative Services').click()
    // cy.get('h1').contains('Creative Services').should('be.visible')
    // cy.title().should('eq', 'Creative Services » Aspiritech')
    // cy.url().should('include', 'creative-services')
    // cy.go('back')
    // home.webDesignDevelopment().should('have.attr', 'href', '/services/web-design-development/').contains('Web Design & Development').click()
    // cy.get('h1').contains('Web Design & Development').should('be.visible')
    // cy.title().should('eq', 'Web Design & Development » Aspiritech')
    // cy.url().should('include', 'web-design-development')
    // cy.go('back')
    // home.automation().should('have.attr', 'href', '/services/automation/').contains('Automation').click()
    // cy.get('h1').contains('Automation').should('be.visible')
    // cy.title().should('eq', 'Automation » Aspiritech')
    // cy.url().should('include', 'automation')
    // cy.go('back')
    // home.managedIt().should('have.attr', 'href', '/services/managed-it//').contains('Managed IT').click()
    // cy.get('h1').contains('Managed IT').should('be.visible')
    // cy.title().should('eq', 'Managed IT » Aspiritech')
    // cy.url().should('include', 'managed-it')
    // cy.go('back')
    home.cybersecurity().should('have.attr', 'href', '/services/cybersecurity/').contains('Cybersecurity').click()
    cy.get('h1').contains('Cybersecurity').should('be.visible')
    cy.title().should('eq', 'Cybersecurity » Aspiritech')
    cy.url().should('include', 'cybersecurity')
    cy.go('back')
    // cy.get('h2').contains('Discover How We Can Help').should('be.visible')
    // cy.get('.yellow').contains('Quality Assurance, End-To-End User Testing, and More').should('have.attr', 'href', '/index.php/services/quality-assurance/').click()
    // cy.get('h1').contains('Software Quality Assurance').should('be.visible')
    // cy.url().should('include', 'quality-assurance')
    // cy.go('back')
    // cy.get('div > .elementor-widget-wrap').should('be.visible').log('Maunal and Automated Testing', 'Audio Testing', 'Data Integrity and Migration')
    // cy.get('h5').contains('All Services').should('be.visible')
    // cy.get('.elementor-widget-container > ul').contains('ul', 'Audio Testing').should('be.visible')
    // cy.get('.elementor-widget-container > ul > :nth-child(1) > a').click()
    // cy.get('h1').contains('Audio & Hardware Testing: Speakers, Headphones, & Connectivity').should('be.visible')
    // cy.url().should('include', 'audio-testing')
    // cy.go('back')
    // cy.get('h2').contains('Our Expertise').should('be.visible')
    // cy.get('.elementor-element-71c39bd > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('a', 'Services').should('have.attr', 'href', '/services/').click()
    // cy.title().should('eq', 'Services » Aspiritech Aspiritech Offers QA Services.')
    // cy.get('h1').contains('Services').should('be.visible')
    // cy.url().should('include', 'services')
    // cy.go('back')
    // cy.get('h2').contains('Our Team').should('be.visible')
    // cy.get('.elementor-button').contains('a', 'About Aspiritech').should('have.attr', 'href', '/about-us/').click()
    // cy.title().should('eq', 'About Us » Aspiritech')
    // cy.url().should('include', 'about-us')
    // cy.get('h1').contains('About Us').should('be.visible')
    // cy.go('back')   
    // cy.get('h2').contains('Our Philosophy').should('be.visible')
    // cy.get('.elementor-element-c15c9a7 > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Our Story').click()
    // cy.title().should('eq', 'Our Story » Aspiritech')
    // cy.url().should('include', 'our-story')
    // cy.get('h1').contains('Our Story').should('be.visible')    
    // cy.go('back')
    //check for the column div
    //home.columndiv()
    //check for the video widget div
    //home.videowidget()
    //check for the video iframe
    //home.videoIframe()
    //load the page and wait for the iframe to load
    //cy.frameLoaded('.elementor-element-1e614d4 .elementor-video-iframe')
    //cy.iframe().find('body').as('iframeBody')
    //play the video
    // cy.get('@iframeBody').find('.elementor-element-1e614d4 .elementor-video-iframe').then(($video) => {
    //   $video[0].play()
    // })
    // cy.wait(10000)
    // cy.get('@iframeBody').find('video').then(($video) => {
    //   $video[0].pause()
    // })
    //Getting first 3 article posts on section News & Resources
    //cy.get('h2').contains('News & Resources').should('be.visible')
    //home.getArticles()
  })

  })
