describe('template spec', () => {
    beforeEach(() => {
        cy.visit('https://aspiritech.org/contact-us/')
        cy.title().should('eq', 'Contact Us – Aspiritech')
        cy.get('.elementor-element-68f10f8 > .elementor-container > .elementor-column > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-heading-title').contains('Contact us').should('be.visible')
    })
    it('passes', () => {
        cy.get('.elementor-element-7d18c61 > .elementor-container > .elementor-column > .elementor-widget-wrap').contains('We’d Love to Hear From You').should('be.visible')
        cy.get('.elementor-element-600bcb5 > .elementor-widget-container > p').contains('Request Our Services').should('be.visible')
        cy.get('.elementor-element-84f53db > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Get in touch').click()
        cy.get('.elementor-element-1de3d926 > .elementor-widget-container > .elementor-heading-title').contains('Work with Us').should('be.visible')
        cy.get('.dialog-close-button > .eicon-close').click()
        cy.get('.elementor-element-e9d406c > .elementor-widget-container > p').contains('Support Aspiritech').should('be.visible')
        cy.get('.elementor-element-284e047 > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Donate now').click()
        cy.get('.elementor-element-e928d8d > .elementor-widget-container > .elementor-heading-title').contains('Support Our Mission').should('be.visible')
        cy.url().should('include', '#donate-now')
        cy.go('back')
        cy.get('.elementor-element-3d978b8 > .elementor-widget-container > p').contains('Media Inquiries').should('be.visible')
        cy.get('.elementor-element-0a03069 > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Send an inquiry').click()
        cy.get('.elementor-element-2bf5131 > .elementor-widget-container > .elementor-heading-title').contains('Media Inquiries').should('be.visible')
        cy.get('.dialog-close-button > .eicon-close').click()
        cy.get('.elementor-element-5c1bd44 > .elementor-widget-container > p').contains('Partnership Inquiries').should('be.visible')
        cy.get('.elementor-element-aa64eb6 > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains("Let's partner").click()
        cy.get('.elementor-element-edd01cf > .elementor-widget-container > .elementor-heading-title').contains('Partnership Inquiries').should('be.visible')
        cy.get('#elementor-popup-modal-9760 > .dialog-widget-content > .dialog-close-button > .eicon-close').click()
        cy.get('.elementor-element-c070257 > .elementor-widget-container > p').contains('Looking for Work?').should('be.visible')
        cy.get('.elementor-element-25ce098 > .elementor-widget-container > .elementor-button-wrapper > .elementor-button').contains('Visit Careers Page').click()
        cy.get('.elementor-element-64bc670 > .elementor-widget-container > .elementor-heading-title').contains('Careers').should('be.visible')
        cy.url().should('include', 'careers')
        cy.go('back')
        cy.get('.elementor-element-6c76d42 > .elementor-widget-container > p').contains('Download Capabilities Statement').should('be.visible')
        cy.request('https://aspiritech.org/wp-content/uploads/2024/02/Aspiritech-Capabilities-Overview-1.pdf')
        .then((response) => {
            expect(response.headers['content-type']).to.include('application/pdf')
          // Handle the response if needed
          // For example, you can check the status code or perform assertions
        })
        cy.get('.elementor-element-69f1d3d > .elementor-widget-container > .elementor-button-wrapper > .elementor-button > .elementor-button-content-wrapper > .elementor-button-text').contains('Download now!')
        .click({force: true, target: 'https://aspiritech.org/wp-content/uploads/2024/02/Aspiritech-Capabilities-Overview-1.pdf'})
      
        //cy.get('.elementor-element-69f1d3d > .elementor-widget-container > .elementor-button-wrapper > .elementor-button')
        //cy.get('.elementor-element-b8c4651 > .elementor-widget-container > h2').should('be.visible')
        //cy.get(':nth-child(1) > a > .elementor-icon-list-text')
        //cy.get(':nth-child(2) > a > .elementor-icon-list-text')
        })
    })
