import Url from "../../../support/PageObjects/url"
import Brokenlinks from "../../../support/PageObjects/brokenlinks"
describe('Contact Us Page', () => {
    let url = new Url()
    let brokenLinks = new Brokenlinks()
    beforeEach(() => {
        url.contactusPage()
        cy.title().should('eq', 'Contact Us – Aspiritech')
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
    })
    it('passes', () => {
        cy.get('h2').contains('We’d Love to Hear From You').should('be.visible')
        cy.get('div > p').contains('Request Our Services').should('be.visible')
        cy.get('a.elementor-button').contains('Get in touch').click()
        cy.get('h2').contains('Work with Us').should('be.visible')
        cy.get('.dialog-close-button > .eicon-close').click()
        cy.get('div > p').contains('Support Aspiritech').should('be.visible')
        cy.get('a.elementor-button').contains('Donate now').click()
        cy.get('h1').contains('Support Our Mission').should('be.visible')
        cy.url().should('include', '#donate-now')
        cy.go('back')
        cy.get('div > p').contains('Media Inquiries').should('be.visible')
        cy.get('a.elementor-button').contains('Send an inquiry').click()
        cy.get('h2').contains('Media Inquiries').should('be.visible')
        cy.get('.dialog-close-button > .eicon-close').click()
        cy.get('div > p').contains('Partnership Inquiries').should('be.visible')
        cy.get('a.elementor-button').contains("Let's partner").click()
        cy.get('h2').contains('Partnership Inquiries').should('be.visible')
        cy.get('#elementor-popup-modal-9760 > .dialog-widget-content > .dialog-close-button > .eicon-close').click()
        cy.get('div > p').contains('Looking for Work?').should('be.visible')
        cy.get('a.elementor-button').contains('Visit Careers Page').click()
        cy.get('h1').contains('Careers').should('be.visible')
        cy.url().should('include', 'careers')
        cy.go('back')
        cy.section('Download Capabilities Statement')
        cy.get('div > p').contains('Download Capabilities Statement').should('be.visible')
        url.capabilitiesStatement()
        cy.get('a.elementor-button').contains('Download now!').click()
        cy.title('eq', 'Aspiritech Capabilities Overview')
        cy.url().should('include', 'Aspiritech-Capabilities-Overview-1.pdf')
        cy.go('back')
        cy.section('Contact Info')
        cy.get('h2').contains('Our office is located in Evanston, IL').should('be.visible')
        cy.get(':nth-child(1) > a > .elementor-icon-list-text').contains('939 Chicago Ave, Evanston, IL 60202 USA').should('be.visible').click()
        cy.go('back')
        cy.get(':nth-child(2) > a > .elementor-icon-list-text').contains('312-945-TEST (8378)').should('be.visible')
        // cy.window().its('navigator').invoke('registerProtocolHandler', 'tel', '/tel/%s').wait(1000, {log: false})// for demo purposes
        // cy.get(':nth-child(2) > a > .elementor-icon-list-text').click()
        // cy.window().its('navigator.href').should('equal', 'tel:+3129458378')
        // cy.contains('a#call', '+1 312-945-TEST (8378)')
        cy.section('Social Media Icons')
        cy.get('.elementor-element-4ab7852 > .elementor-widget-container > .elementor-icon-wrapper').click()
        cy.title().should('eq', 'Aspiritech | LinkedIn')
        cy.url().should('include', 'aspiritech')
        cy.go('back')
        //cy.get('.elementor-element-d9284dc > .elementor-widget-container > .elementor-icon-wrapper').click()
        //cy.url().should('include', 'aspiritech')
        //cy.get('.elementor-element-3f84835 > .elementor-widget-container > .elementor-icon-wrapper').click()
        //cy.url().should('include', 'login')
        //cy.go('back')
        // cy.get('.elementor-element-83f3cec > .elementor-widget-container > .elementor-icon-wrapper').click()
        // cy.url().should('include', 'aspiritech')
        // cy.go('back')
        })
        brokenLinks.option1()
    })
