describe('template spec', () => {
    beforeEach(() => {
        cy.visit('https://aspiritech.org/services/accessibility/')
        cy.title().should('eq', 'Accessibility Testing: Design, UX, Usability, & WCAG Conformance – Aspiritech')
        cy.get('.elementor-element-4fb348f1 > .elementor-widget-container > .elementor-heading-title').contains('Accessibility Testing: Design, UX, Usability, & WCAG Conformance').should('be.visible')
    })
    it('passes', () => {
        cy.get('.elementor-widget-container > .yellow').contains('Book your discovery call now').click()
        cy.get('.elementor-element-68f10f8 > .elementor-container > .elementor-column > .elementor-widget-wrap').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        cy.get('.elementor-element-c81d9d6 > .elementor-widget-container > .elementor-image-box-wrapper > .elementor-image-box-content > .elementor-image-box-title > a').contains('The Business Case for Accessibility').should('be.visible')
        cy.get('.elementor-element-260fb13 > .elementor-widget-container > .elementor-heading-title > a').contains('View all case studies').click()
        cy.get('.elementor-element-04c4dba > .elementor-widget-container > .elementor-heading-title').contains('Case Studies').should('be.visible')
        cy.url().should('include', 'case-studies')
        cy.go('back')
        cy.get('.post-10858 > .elementor-post__card > .elementor-post__text > .elementor-post__title').contains('SourceAmerica Case Study').click()
        cy.get('.elementor-element-fce111c > .elementor-widget-container > .elementor-heading-title').contains('SourceAmerica Case Study').should('be.visible')
        cy.url().should('include', 'source-america-case-study')
        cy.go('back')
        cy.get('.post-9974 > .elementor-post__card > .elementor-post__text > .elementor-post__title').contains('Aon Accessibility Audit Case Study').click()
        cy.get('.elementor-element-fce111c > .elementor-widget-container > .elementor-heading-title').contains('Aon Accessibility Audit Case Study').should('be.visible')
        cy.url('include', 'aon-accessibility-audit-case-study')
        cy.go('back')
        cy.get('p > .yellow').click()
        cy.get('.elementor-element-68f10f8 > .elementor-container > .elementor-column > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        })
    })
