import Url from "../../../support/PageObjects/url"
import Brokenlinks from "../../../support/PageObjects/brokenlinks"
describe('template spec', () => {
    let url = new Url()
    let brokenLinks = new Brokenlinks()
    beforeEach(() => {
        url.accessibilityPage()
        cy.title().should('eq', 'Accessibility Testing: Design, UX, Usability, & WCAG Conformance – Aspiritech')
        cy.get('h1').contains('Accessibility Testing: Design, UX, Usability, & WCAG Conformance').should('be.visible')
    })
    it('passes', () => {
        cy.get('div.elementor-widget-container > .yellow').contains('Book your discovery call now').click()
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        cy.get('div.elementor-widget-container').contains('The Business Case for Accessibility').click({force: true})
        cy.get('h1').contains('The Business Case for Digital Accessibility').should('be.visible')
        cy.title().should('eq', 'The Business Case for Digital Accessibility – Aspiritech')
        cy.url().should('include', 'business-case-for-accessibility')
        cy.go('back')
        url.accessibilitybusinessCase()
        cy.get('div.elementor-widget-container').contains('View all case studies').click()
        cy.get('h1').contains('Case Studies').should('be.visible')
        cy.url().should('include', 'case-studies')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('SourceAmerica Case Study').click()
        cy.get('h1').contains('SourceAmerica Case Study').should('be.visible')
        cy.url().should('include', 'source-america-case-study')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('Aon Accessibility Audit Case Study').click()
        cy.get('h1').contains('Aon Accessibility Audit Case Study').should('be.visible')
        cy.url('include', 'aon-accessibility-audit-case-study')
        cy.go('back')
        cy.get('p > .yellow').click()
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        })
        brokenLinks.option1()
    })
