describe('template spec', () => {
    beforeEach(() => {
        cy.visit('https://aspiritech.org/services/audio-testing/')
        cy.title().should('eq', 'Audio & Hardware Testing: Speakers, Headphones, & Connectivity – Aspiritech')
        cy.get('h1').contains('Audio & Hardware Testing: Speakers, Headphones, & Connectivity').should('be.visible')
    })
    it('passes', () => {
        cy.get('.underline').contains('case study of one of our biggest clients').click()
        cy.get('h1').contains('Bose Hardware QA & Product Excellence Case Study').should('be.visible')
        cy.url().should('include', 'bose-case-study')
        cy.go('back')
        cy.get('.elementor-widget-container > :nth-child(2) > a > i').contains('If so, contact our team and find out how we can help.').click()
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        cy.get('.elementor-widget-container > .yellow').contains('Book your discovery call now').click()
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        cy.get('.elementor-element-bc7b3d2 > .elementor-widget-container > .elementor-heading-title > a').contains('View all case studies').click()
        cy.get('h1').contains('Case Studies').should('be.visible')
        cy.url().should('include', 'case-studies')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('Bose Case Study').click()
        cy.get('h1').contains('Bose Hardware QA & Product Excellence Case Study').should('be.visible')
        cy.url().should('include', 'bose-case-study')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('IDEXX Case Study').click()
        cy.get('h1').contains('IDEXX QA & Product Excellence Case Study').should('be.visible')
        cy.url().should('include', 'idexx-case-study')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('Zebra Case Study').click()
        cy.get('h1').contains('Zebra Hardware QA & Product Excellence Case Study').should('be.visible')
        cy.url().should('include', 'zebra-case-study')
        cy.go('back')
        cy.get('p > .yellow').click()
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
    })
    it('Finds all broken links', () => {
        cy.get('a').each(link => {
            if (link.prop('href'))
                cy.request({
                    url: link.prop('href'),
                    failOnStatusCode: false
                })
            cy.log(link.prop('href'))
        })
    })
})    