describe('template spec', () => {
    beforeEach(() => {
        cy.visit('https://aspiritech.org/services/data-services/')
        cy.title().should('eq', 'Data Services: Data Annotation, Data Labeling, and Data Validation. – Aspiritech')
        cy.get('.elementor-element-63b8939c > .elementor-widget-container > .elementor-heading-title').contains('Data Services: Data Annotation, Data Labeling, and Data Validation.').should('be.visible')
    })
    it('passes', () => {
        cy.get('strong > a').contains('Contact us').click()
        cy.get('.elementor-element-68f10f8 > .elementor-container > .elementor-column > .elementor-widget-wrap').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        cy.get('.elementor-element-50d17da8 > .elementor-widget-container > p > .yellow').contains('Book your discovery call now').click()
        cy.get('.elementor-element-68f10f8 > .elementor-container > .elementor-column > .elementor-widget-wrap').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        cy.get('.elementor-element-3de5bc4 > .elementor-widget-container > .elementor-heading-title > a').contains('View all case studies').click()
        cy.get('.elementor-element-04c4dba > .elementor-widget-container > .elementor-heading-title').contains('Case Studies').should('be.visible')
        cy.url().should('include', 'case-studies')
        cy.go('back')
        cy.get('.post-10868 > .elementor-post__card > .elementor-post__text > .elementor-post__title').contains('ANC & TSA Case Study').click()
        cy.get('.elementor-element-fce111c > .elementor-widget-container > .elementor-heading-title').contains('ANC & the TSA Case Study').should('be.visible')
        cy.url().should('include', 'anc-tsa-case-study')
        cy.go('back')
        cy.get('.post-9962 > .elementor-post__card > .elementor-post__text > .elementor-post__title').contains('Aon Benefits Calculator Case Study').click()
        cy.get('.elementor-element-fce111c > .elementor-widget-container > .elementor-heading-title').contains('Aon Benefits Calculator Case Study').should('be.visible')
        cy.url().should('include', 'aon-benefits-calculator')
        cy.go('back')
        cy.get('.post-4368 > .elementor-post__card > .elementor-post__text > .elementor-post__title').contains('JP Morgan Chase').click()
        cy.get('.elementor-element-13eee0c0 > .elementor-widget-container > .elementor-heading-title').contains('JP Morgan Chase QA & Product Excellence Case Study').should('be.visible')
        cy.url().should('include', 'jp-morgan-chase')
        cy.go('back')
        cy.get('.elementor-element-7bfa1e0 > .elementor-widget-container > p > .yellow').contains('We can’t wait to hear from you!').click()
        cy.get('.elementor-element-68f10f8 > .elementor-container > .elementor-column > .elementor-widget-wrap > .elementor-element > .elementor-widget-container > .elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        })
    })
