import Url from "../../../support/PageObjects/url"
import Brokenlinks from "../../../support/PageObjects/brokenlinks"
describe('Data Services Page', () => {
    let url = new Url()
    let brokenLinks = new Brokenlinks()
    beforeEach(() => {
        url.dataservicesPage()
        cy.title().should('eq', 'Data Services: Data Annotation, Data Labeling, and Data Validation. – Aspiritech')
        cy.get('h1').contains('Data Services: Data Annotation, Data Labeling, and Data Validation.').should('be.visible')
    })
    it('passes', () => {
        cy.get('strong > a').contains('Contact us').click()
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        cy.get('a.yellow').contains('Book your discovery call now').click()
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        cy.get('a').contains('View all case studies').click()
        cy.get('h1').contains('Case Studies').should('be.visible')
        cy.url().should('include', 'case-studies')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('ANC & TSA Case Study').click()
        cy.get('h1').contains('ANC & the TSA Case Study').should('be.visible')
        cy.url().should('include', 'anc-tsa-case-study')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('Aon Benefits Calculator Case Study').click()
        cy.get('h1').contains('Aon Benefits Calculator Case Study').should('be.visible')
        cy.url().should('include', 'aon-benefits-calculator')
        cy.go('back')
        cy.get('h3.elementor-post__title').contains('JP Morgan Chase').click()
        cy.get('h1').contains('JP Morgan Chase QA & Product Excellence Case Study').should('be.visible')
        cy.url().should('include', 'jp-morgan-chase')
        cy.go('back')
        cy.get('a.yellow').contains('We can’t wait to hear from you!').click()
        cy.get('span.elementor-heading-title').contains('Contact us').should('be.visible')
        cy.url().should('include', 'contact-us')
        cy.go('back')
        })
        brokenLinks.option1()
    })
